W3ExeSolution-war/src/fit5042/tutex/mbeans/PropertyManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 */
package fit5042.tutex.mbeans;

import fit5042.tutex.calculator.CompareProperty;
import fit5042.tutex.repository.PropertyRepository;
import fit5042.tutex.repository.entities.Address;
import fit5042.tutex.repository.entities.ContactPerson;
import fit5042.tutex.repository.entities.Property;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

/**
 *
 * @author messomc
 * @author guan
 *
 */
@ManagedBean(name = "propertyManagedBean", eager = true)
@SessionScoped

public class PropertyManagedBean implements Serializable {
    
	@EJB
	private CompareProperty compareProperty;
	
	@EJB
	private PropertyRepository propertyRepository;
	
    private int bestPerRoom;
    private int selectedId;

    public int getSelectedId() {
        return selectedId;
    }

    public void setSelectedId(int selectedId) {
        this.selectedId = selectedId;
    }

    public int getBestPerRoom() {
        return bestPerRoom;
    }

    public void setBestPerRoom(int bestPerRoom) {
        this.bestPerRoom = bestPerRoom;
    }
    
    /**
     * Creates a new instance of PropertyManagedBean
     */
    public PropertyManagedBean() {
        selectedId = 0;
//        compareProperty = new ComparePropertySessionBean();
    }

    public List<Property> getAllProperties() {
        try {
            List<Property> properties = propertyRepository.getPropertyList();
            return properties;
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    public void addProperty(Property property) {
    	Property p = convertPropertyToEntity(property);

        try {
        	propertyRepository.addProperty(p);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Search a property by Id
     */
    public Property searchPropertyById(int id) {
        try {
            return propertyRepository.searchPropertyById(id);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }

    public Set<Property> searchPropertyByContactPersonId(int contactPersonId) {
        try {
            //retrieve contact person by id
            for (ContactPerson contactPerson : propertyRepository.getAllContactPeople()) {
                if (contactPerson.getConactPersonId() == contactPersonId) {
                    return propertyRepository.searchPropertyByContactPerson(contactPerson);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }

    public List<ContactPerson> getAllContactPeople() throws Exception {
        try {
            return propertyRepository.getAllContactPeople();
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }

    public void removeProperty(int propertyId) {
        try {
        	propertyRepository.removeProperty(propertyId);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void editProperty(Property property) {
        try {
            String s = property.getAddress().getStreetNumber();
            Address address = property.getAddress();
            address.setStreetNumber(s);
            property.setAddress(address);

            propertyRepository.editProperty(property);

            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Property has been updated succesfully"));
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public List<Property> searchPropertyByBudget(double budget) {
        try {
            return propertyRepository.searchPropertyByBudget(budget);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }


    private Property convertPropertyToEntity(Property localProperty) {
        try {
            Property property = new Property(); //entity
            String streetNumber = localProperty.getStreetNumber();
            String streetAddress = localProperty.getStreetAddress();
            String suburb = localProperty.getSuburb();
            String postcode = localProperty.getPostcode();
            String state = localProperty.getState();
            Address address = new Address(streetNumber, streetAddress, suburb, postcode, state);
            property.setAddress(address);
            property.setNumberOfBedrooms(localProperty.getNumberOfBedrooms());
            property.setPrice(localProperty.getPrice());
            property.setSize(localProperty.getSize());
            property.setPropertyId(localProperty.getPropertyId());
            property.setTags(localProperty.getTags());
            property.setContactPerson(localProperty.getContactPerson());
            return property;
        } catch (Exception ex) {

        }
        return null;
    }

     public void addPropertyID() {
        compareProperty.addProperty(searchPropertyById(selectedId));
        selectedId = 0;
    }
    
    public void removePropertyID() {
        compareProperty.removeProperty(searchPropertyById(selectedId));
        selectedId = 0;
    }    
    
    public String bestPerRoom()
    {
        bestPerRoom = compareProperty.bestPerRoom();
        return "index";
    }
    
    public int getFinalPropertyId() {
    	return propertyRepository.getPropertyId();
    }
    
}

W3ExeSolution-war/WebContent/add.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:head>
	<h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
	<h:outputStylesheet library="css" name="style.css"></h:outputStylesheet>
	<title>#{titleController.pageTitle}</title>
</h:head>
<h:body>
	<div class="container">
		<div class="navbar navbar-inverse">
			<div class="navbar-brand">#{titleController.pageTitle} - Add
				Property</div>
		</div>
		<div>
			<f:view>
				<h:form>
					<h1>
						<h:outputText value="Create" />
					</h1>
					<table class="table table-bordered ">
						<tr class="#{!streetNumber.valid ? 'has-error' : 'none'}">
							<td width="200"><h:outputLabel value="streetNumber"
									for="streetNumber" /></td>
							<td><h:inputText id="streetNumber"
									value="#{property.streetNumber}" title="streetNumber"
									required="true"
									requiredMessage="Please enter the street number!"
									validatorMessage="Please enter a street number between 1 and 1000"
									converterMessage="Please enter a number" pt:placeholder="900">
									<f:convertNumber integerOnly="true" />
									<f:validateLongRange minimum="1" maximum="1000" />
								</h:inputText> <br /> <h:message for="streetNumber"
									class="#{!streetNumber.valid ? 'label label-warning' : 'none'}" />
							</td>
						</tr>

						<tr class="#{!streetAddress.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="streetAddress" for="streetAddress" />
							</td>
							<td><h:inputText id="streetAddress"
									value="#{property.streetAddress}" title="streetAddress"
									required="true"
									requiredMessage="Please enter the street address!"
									pt:placeholder="Dandenong Rd" /> <br /> <h:message
									for="streetAddress"
									class="#{!streetAddress.valid ? 'label label-warning' : 'none'}" />
							</td>

						</tr>

						<tr class="#{!suburb.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="suburb" for="suburb" /></td>
							<td><h:inputText id="suburb" value="#{property.suburb}"
									title="suburb" required="true"
									requiredMessage="Please enter the suburb!"
									pt:placeholder="Caulfield East" /> <br /> <h:message
									for="suburb"
									class="#{!suburb.valid ? 'label label-warning' : 'none'}" /></td>

						</tr>

						<tr class="#{!state.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="state" for="state" /></td>
							<td><h:inputText id="state" value="#{property.state}"
									title="state" size="3" required="true"
									requiredMessage="Please enter the state!" pt:placeholder="VIC" />
								<br /> <h:message for="state"
									class="#{!state.valid ? 'label label-warning' : 'none'}" /></td>

						</tr>
						<tr class="#{!postcode.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="postcode" for="postcode" /></td>
							<td><h:inputText id="postcode" value="#{property.postcode}"
									title="postcode" required="true"
									requiredMessage="Please enter the postcode!"
									validatorMessage="Please enter a postcode between 0200 and 4700"
									converterMessage="Please enter a number" pt:placeholder="3145">
									<f:convertNumber integerOnly="true" />
									<f:validateLongRange minimum="200" maximum="4700" />
								</h:inputText> <br /> <h:message for="postcode"
									class="#{!postcode.valid ? 'label label-warning' : 'none'}" />
							</td>

						</tr>
						<tr>
							<td><h:outputLabel value="Size:" for="size" /></td>
							<td><h:inputText id="size" value="#{property.size}"
									title="Size" required="true"
									requiredMessage="Please enter the size!"
									validatorMessage="Size must be larger than 1"
									converterMessage="Please enter a positive number"
									pt:placeholder="530000.59">
									<f:convertNumber minFractionDigits="2" />
									<f:validateLongRange minimum="1" />
								</h:inputText> <br /> <h:message for="size"
									class="#{!size.valid ? 'label label-warning' : 'none'}" /></td>

						</tr>

						<tr>
							<td><h:outputLabel value="NumberOfBedrooms:"
									for="numberOfBedrooms" /></td>
							<td><h:inputText id="numberOfBedrooms"
									value="#{property.numberOfBedrooms}" title="NumberOfBedrooms"
									required="true"
									requiredMessage="Please enter the number of bedrooms!"
									validatorMessage="The number of bedrooms must be larger than or equal to 0"
									converterMessage="Please enter a number" pt:placeholder="4">
									<f:convertNumber integerOnly="true" />
									<f:validateLongRange minimum="0" />
								</h:inputText> <br /> <h:message for="numberOfBedrooms"
									class="#{!numberOfBedrooms.valid ? 'label label-warning' : 'none'}" />
							</td>

						</tr>

						<tr>
							<td><h:outputLabel value="Price:" for="price" /></td>
							<td><h:inputText id="price" value="#{property.price}"
									title="Price" required="true"
									requiredMessage="Please enter the price!"
									validatorMessage="The price must larger than $1"
									converterMessage="Please enter a price"
									pt:placeholder="$100000.00">
									<f:convertNumber currencySymbol="$" type="currency" />
									<f:validateLongRange minimum="1" />
								</h:inputText> <br /> <h:message for="price"
									class="#{!price.valid ? 'label label-warning' : 'none'}" /></td>

						</tr>
						<tr>
							<td><h:outputLabel value="Contact Person:" for="contact" /></td>
							<td><h:selectOneMenu id="contact"
									value="#{property.contactPerson}" converter="contactPerson">
									<f:selectItem itemValue="#{null}" itemLabel="--select--" />
									<f:selectItems value="#{propertyManagedBean.allContactPeople}"
										var="c" itemLabel="#{c.name}" itemValue="#{c}" />
								</h:selectOneMenu></td>
						</tr>

					</table>

					<h:commandButton id="submit" value="Submit"
						action="#{addProperty.addProperty(property)}"
						class="btn btn-primary" />
					<h:link id="close" value="Close" outcome="faces/index.xhtml"
						class="btn btn-primary" />

				</h:form>

			</f:view>
		</div>
	</div>

</h:body>
</html>

W3ExeSolution-war/WebContent/detail.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"      
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title> 
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - View Property
                </div>
            </div>

            <h:form id="MyForm">
                <table class="table table-bordered ">
                    <tr>
                        <td width ="150" valign="top">Id:</td>

                        <td valign="bottom">
                            <h:outputLabel id = "Id" >#{propertyController.property.propertyId}</h:outputLabel>    
                           
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Address:</td>

                        <td valign="bottom">
                            <h:outputLabel id = "Address" >#{propertyController.property.address}</h:outputLabel>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">No of Bedrooms: </td>

                        <td valign="bottom">
                            <h:outputLabel id = "No-Bedrooms" >#{propertyController.property.numberOfBedrooms}</h:outputLabel>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Price: </td>

                        <td valign="bottom">
                            <h:outputLabel id = "Price" >
                                #{propertyController.property.price}
                                <f:convertNumber currencyCode="AUD" type="currency" />
                            </h:outputLabel>    

                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Size: </td>

                        <td valign="bottom">
                            <h:outputLabel id = "Size" >#{propertyController.property.size}</h:outputLabel>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Contact Person: </td>

                        <td valign="bottom">
                            <h:outputLabel id = "ContactName" >#{propertyController.property.contactPerson.toString()}</h:outputLabel>    
                        </td>
                    </tr>


                </table>   
                <h:link id="close" value="Close" outcome="faces/index.xhtml"
						class="btn btn-primary" />

            </h:form>
        </div>
    </h:body>
</html>

W3ExeSolution-war/WebContent/edit.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"      
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title> 
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Edit Property
                </div>
            </div>

            <h:form id="MyForm">
                <table class="table table-bordered ">

                    <tr>
                        <td width ="150" valign="top">Id:</td>

                        <td valign="bottom">
                            <h:outputLabel id = "Id" >#{propertyController.property.propertyId}</h:outputLabel>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Street number: </td>
                        <td valign="bottom">
                            <h:inputText id = "streetNumber" value="#{propertyController.property.address.streetNumber}" binding="#{streetNumber}" required="true"
                                         validatorMessage="Please enter a valid street number."
                                         requiredMessage="Please enter an street number. "></h:inputText>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Street address: </td>
                        <td valign="bottom">
                            <h:inputText id = "streetAddress" value="#{propertyController.property.address.streetAddress}" binding="#{streetAddress}" required="true"
                                         validatorMessage="Please enter a valid street address."
                                         requiredMessage="Please enter an street address. "></h:inputText>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Suburb: </td>
                        <td valign="bottom">
                            <h:inputText id = "suburb" value="#{propertyController.property.address.suburb}" binding="#{suburb}" required="true"
                                         validatorMessage="Please enter a valid suburb."
                                         requiredMessage="Please enter a suburb. "></h:inputText>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">State: </td>
                        <td valign="bottom">
                            <h:inputText id = "state" value="#{propertyController.property.address.state}" binding="#{state}" required="true"
                                         validatorMessage="Please enter a valid state."
                                         requiredMessage="Please enter a state. "></h:inputText>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Postcode: </td>
                        <td valign="bottom">
                            <h:inputText id = "postcode" value="#{propertyController.property.address.postcode}" binding="#{postcode}" required="true"
                                         validatorMessage="Please enter a valid postcode."
                                         requiredMessage="Please enter a postcode. "></h:inputText>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">No of Bedrooms: </td>

                        <td valign="bottom">
                            <h:inputText id = "No-Bedrooms" value="#{propertyController.property.numberOfBedrooms}"  required="true"
                                         validatorMessage="Number of rooms must be greater than 0"
                                         requiredMessage="Please enter number of rooms. "></h:inputText>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Price: </td>

                        <td valign="bottom">
                            <h:inputText id = "Price" value="#{propertyController.property.price}"  required="true"
                                         validatorMessage="Please enter a value greater than 0.0"
                                         requiredMessage="Please enter a price. ">

                                <f:convertNumber currencyCode="AUD" type="currency" />
                            </h:inputText>    

                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Size: </td>

                        <td valign="bottom">
                            <h:inputText id = "Size" value="#{propertyController.property.size}"  required="true"
                                         validatorMessage="Please enter a value greater than 0.0"
                                         requiredMessage="Please enter a size. "></h:inputText>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Contact Person: </td>
                        <td>
                            <h:selectOneMenu id="contact" value="#{propertyController.property.contactPerson}" converter="contactPerson">
                                <f:selectItem itemValue="#{null}" itemLabel="--select--" />
                                <f:selectItems value="#{propertyManagedBean.allContactPeople}" var="c"  
                                               itemLabel="#{c.name}" itemValue="#{c}" />
                            </h:selectOneMenu>
                        </td>
                    </tr>             
                </table>

                <h:commandButton id="save" value="Save" action="#{propertyManagedBean.editProperty(propertyController.property)}"  class="btn btn-primary" >
                    <f:param name="propertyID" value="#{propertyController.propertyId+1}"/>
                </h:commandButton>
                <h:link id="close" value="Close" outcome="faces/index.xhtml"
						class="btn btn-primary" />
            </h:form>
        </div>
    </h:body>
</html>

W3ExeSolution-war/WebContent/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
<h:head>
	<h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
	<title>#{titleController.pageTitle}</title>
</h:head>
<h:body>
	<div class="container">
		<div class="navbar navbar-inverse">
			<div class="navbar-brand">#{titleController.pageTitle} -
				Property List</div>
		</div>

		<h:form id="MyForm">
			<table class="table table-bordered table-striped">
				<!-- For each property in properties ArrayList... -->
				<tr>
					<td><h:outputLabel id="Id" value="Id" /></td>
					<td><h:outputLabel id="Price" value="Price" /></td>

					<td><h:outputLabel id="Address" value="Address" /></td>

				</tr>

				<ui:repeat id="Myrepeat" value="#{propertyApplication.properties}"
					var="property" varStatus="status">

					<tr
						onclick="document.getElementById('MyForm:principle').value = document.getElementById('MyForm:Myrepeat:#{status.index}:outPrice').textContent;
                            document.getElementById('MyForm:selectedId').value = document.getElementById('MyForm:Myrepeat:#{status.index}:MainPropertyID').textContent;">
						<td><h:outputText
								value="#{propertyApplication.properties.get(status.index).propertyId}"
								id="MainPropertyID" /></td>

						<td><h:outputText id="outPrice"
								value="#{propertyApplication.properties.get(status.index).price}" />
						</td>
						<td><h:outputText id="outAddress"
								value="#{propertyApplication.properties.get(status.index).address}"></h:outputText>
						</td>
						<td><h:link value="View | " outcome="faces/detail.xhtml">
								<!-- pass the parameter to next page, the param name is propertyID, and the value is index + 1.
                                  You can get the value from next page using the indexController -->
								<f:param name="propertyID" value="#{status.index + 1}" />
							</h:link> <h:link value="Edit | " outcome="faces/edit.xhtml">
								<!-- pass the parameter to next page, the param name is propertyID, and the value is index + 1.
                                  You can get the value from next page using the indexController -->
								<f:param name="propertyID" value="#{status.index + 1}" />
							</h:link> <h:commandLink value="Delete"
								action="#{removeProperty.removeProperty(propertyApplication.properties.get(status.index).propertyId)}"
								disabled="#{propertyApplication.properties.get(status.index).propertyId == null}">
							</h:commandLink> <h:outputText value=" " /></td>

					</tr>

				</ui:repeat>

			</table>

			<div>
				<h:commandButton id="add" value="Add" action="add.xhtml"
					class="btn btn-primary" />
				&nbsp; &nbsp;
				<h:commandButton id="viewAll" value="View All"
					action="#{searchProperty.searchAll()}" class="btn btn-primary">
					<f:param name="propertyID" value="#{status.index + 1}" />
				</h:commandButton>
			</div>
			<div>
				<h:inputText value="#{searchProperty.searchByInt}" id="searchById"
					required="true"
					onchange="if (document.getElementById('MyForm:searchById').value.trim() == '') {document.getElementById('MyForm:searchById').value = 0;} " />
				<h:commandButton id="searchId" value="Search by Id"
					action="#{searchProperty.searchPropertyById(searchProperty.searchByInt)}"
					class="btn btn-primary">
					<f:param name="propertyID" value="#{status.index + 1}" />
				</h:commandButton>

				<h:inputText value="#{searchProperty.searchByDouble}"
					id="searchByBudget" required="true"
					onchange="if (document.getElementById('MyForm:searchByBudget').value.trim() == '') {document.getElementById('MyForm:searchByBudget').value = 0.0;} " />
				<h:commandButton id="searchBudget" value="Search by Budget"
					action="#{searchProperty.searchPropertyByBudget(searchProperty.searchByDouble)}"
					class="btn btn-primary">
					<f:param name="propertyID" value="#{status.index + 1}" />
				</h:commandButton>


				<h:selectOneMenu id="contact"
					value="#{searchProperty.contactPersonId}">
					<f:selectItem itemValue="#{null}" itemLabel="--select--" />
					<f:selectItems value="#{propertyManagedBean.allContactPeople}"
						var="c" itemLabel="#{c.name}" itemValue="#{c.conactPersonId}" />
				</h:selectOneMenu>
				<h:commandButton id="searchByContact" value="Search by Contact"
					action="#{searchProperty.searchPropertyByContactPersonId(searchProperty.contactPersonId)}"
					class="btn btn-primary">
					<f:param name="propertyID" value="#{status.index + 1}" />
				</h:commandButton>
			</div>
			<div>
				<br />
				<hr style="border-color: lightgrey;" />
				<table>
					<tr>
						<td width="500"><b>Loan Monthly Payment Calculation</b></td>
						<td><b>Comparing Properties</b></td>
					</tr>
				</table>
			</div>

			<br />
			<br />
			<table>

				<tr>
					<td width="180">Principle(click on property):</td>
					<td width="320"><h:inputText id="principle"
							value="#{loanManagedBean.loan.principle}" validatorMessage="Error value must be above 1000">
							<f:converter converterId="javax.faces.Double" />
							<f:validateDoubleRange minimum="1000" />
						</h:inputText> <h:message for="principle" style="color:red"/></td>
					<td>Selected property id:</td>
					<td><h:inputText id="selectedId"
							value="#{propertyManagedBean.selectedId}"></h:inputText></td>

				</tr>
				<tr>
					<td>Interest Rate:</td>
					<td><h:selectOneListbox
							value="#{loanManagedBean.loan.interestRate}" size="3">
							<f:selectItem itemValue="0.01" itemLabel="0.01" />
							<f:selectItem itemValue="0.02" itemLabel="0.02" />
							<f:selectItem itemValue="0.03" itemLabel="0.03" />
							<f:selectItem itemValue="0.04" itemLabel="0.04" />
							<f:selectItem itemValue="0.05" itemLabel="0.05" />
							<f:selectItem itemValue="0.06" itemLabel="0.06" />
							<f:selectItem itemValue="0.07" itemLabel="0.07" />

						</h:selectOneListbox></td>
					<td></td>
					<td><h:commandButton id="addCompare" value="AddCompare"
							action="#{propertyManagedBean.addPropertyID()}" />&nbsp; &nbsp;
						<h:commandButton id="removeCompare" value="RemoveCompare"
							action="#{propertyManagedBean.removePropertyID()}" /></td>

				</tr>
				<tr>
					<td>Number of Years:</td>
					<td><h:inputText id="numberOfYears"
							value="#{loanManagedBean.loan.numberOfYears}">
							<f:converter converterId="javax.faces.Integer" />
						</h:inputText></td>
					<td></td>
					<td><h:commandButton id="bestPerRoom" value="BestPerRoom"
							action="#{propertyManagedBean.bestPerRoom()}" />&nbsp; &nbsp; <h:outputLabel
							id="bestPropertyId" value="#{propertyManagedBean.bestPerRoom}" />
					</td>
				</tr>
				<tr>
					<td>Monthly Payment:</td>
					<td colspan="3"><h:outputLabel id="monthlyPayment"
							value="#{loanManagedBean.loan.monthlyPayment}">
							<f:convertNumber currencyCode="AUD" type="currency" />
						</h:outputLabel></td>
				</tr>
				<tr>
					<td colspan="4"><h:commandButton id="calculate"
							value="Calculate" action="#{loanManagedBean.calculate()}" /></td>

				</tr>
			</table>


		</h:form>
	</div>
</h:body>
</html>